### PR TITLE
add other music functions: harmonicsByFret, harmonicsByRatio, harmoni…

### PR DESCRIPTION
**Pull request by fedelibre**
…cNote, harmonicsOn

I often use \harmonicByFret function.. While checking the [music functions appendix](http://www.lilypond.org/doc/v2.19/Documentation/notation/available-music-functions) I found also some other words missing.

### CODE REVIEW

**Comment by uliska** [comment]
I'm not sure about this but I *think* Frescobaldi retrieves this information from LilyPond through a script, but only supports the latest stable release. IIRC an earlier merge request by me wasn't merged for that reason.

**Comment by fedelibre** [comment]
I think that all these commands were present in 2.18.2. If it's like you say, then the script has a bug?

**Comment by PeterBjuhr** [comment]
> I'm not sure about this but I think Frescobaldi retrieves this information from LilyPond through a script [...]

I think it's [_lilypond_data.py](https://github.com/wbsoft/python-ly/blob/master/ly/data/_lilypond_data.py) that is generated...

**Comment by PeterBjuhr** [comment]
> [...] an earlier merge request by me [...]

For those who are curious (like me obviously) see: https://github.com/wbsoft/frescobaldi/pull/203

**Comment by wbsoft** [comment]
Question: was this data aquired by running LilyPond on the getdata.ly script? (See wbsoft/frescobaldi#203)

**Comment by fedelibre** [comment]
No, I added it manually. I learned about this getdata.ly stuff afterwards.
However, I've launched the script right now using lilypond 2.19.35 and it brings many changes to _lilypond_data.py but not those I've done manually (this was expected, since, as I wrote before, these commands are not recent).

    cd ly/data
    make -B LILYPOND=/home/fede/bin/lilypond

**Comment by fedelibre** [comment]
I just realized that  LilyPond reserved words for auto completion and highlighting  are defined **manually** in `ly/words.py`. Correct?
If there are no objections I'll upload a new patch to this pull request.

**Comment by uliska** [comment]
At least I can confirm that the data produced from `getdata.ly` doesn't include keywords, but only

```
  - version: the lilypond version string
  - interfaces: maps interface names to the list of their properties
  - grobs: maps grob names to the list of interfaces they implement
  - contextproperties: the list of all-user-translation-properties
  - musicglyphs: the list of all glyphs in the feta font
```

**Comment by fedelibre** [comment]
I've just forced a new patch, where I've added slashedGrace and left the trailing spaces (so the diff is clear).

**Comment by fedelibre** [comment]
@PeterBjuhr I've rebased the patch to resolve the conflicts.

Some of the keywords were added by new commits, but the "since version" was not correct. On this regard, I think it makes more sense to always use the stable version even if the keyword was added (obviously) during a development release.

**Pull request merged**
