### PR TITLE
Prepare for 0.9.9 release

### PR DESCRIPTION
**Pull request by fedelibre**
I've set 13th of December as release date, as we might need some time to review again the LilyPond syntax and other stuff.

### CODE REVIEW

**Comment by fedelibre** [comment]
@igneus You've worked on the tests before... Do you know why they are failing?
You are likely the one who caused this failing :-)

I see an inconsistent use of utf-8 vs UTF-8. I thought that UTF-8 is more correct?

I understand that it's the `compare_output` function that is failing.
The tests output don't print much useful information, but if I grep some words I find that one of the files that are failing is `tests/test_xml_files/markup.ly`, which now produces a different `tests/test_xml_files/markup.xml`. Right?

I don't know MusicXML at all.

**Comment by igneus** [comment]
@fedelibre In fact I found most tests failing and in #170 I fixed all which were "just broken tests" (i.e. the code under test worked, just the expected output was out of sync with developments of the codebase). I intentionally left two failing tests, because the results were obviously incorrect. I'll check current state of the affairs later today.

**Comment by igneus** [comment]
... but yes, in one sense I am the one who caused the tests failing: I made them run automatically and publicly. Prior to #170 they were only run manually (if anyone cared to run them), now they run on each push and each pull request.

**Comment by igneus** [comment]
@fedelibre Would it be acceptable to mark the two failing tests as known failures (I will provide code for that), so the test suite will pass, and open an issue to keep track of this (or reopen #153)? I will be happy to look more into this, but I definitely won't make the December 13th deadline.

It should be also kept in mind that python-ly version is printed in the MusicXML output, so once the package version is updated, version in the example XML files must be updated, too. Otherwise all tests will be failing.

**Comment by fedelibre** [comment]
Yes, of course.Please go ahead and feel free to add your commits in this branch. Thanks

**Comment by fedelibre** [comment]
I made a little change in the first commit: I changed the release date to 20/12 and added the link to the list of commits of 0.9.9 tag.

I'll merge this PR next week.

**Pull request merged**
