### PR TITLE
Remove unused music commands that haven't been in LilyPond since 2.17.25

### PR DESCRIPTION
**Pull request by ksnortum**

### CODE REVIEW

**Review by fedelibre — COMMENTED** [review]
I guess that you took the list from [this convert-ly rule](https://gitlab.com/lilypond/lilypond/-/blob/master/python/convertrules.py?ref_type=heads#L3826).

I wonder if we should rather remove these lines instead of comment them.
@PeterBjuhr @jeanas what do you think?

**Comment by ksnortum** [comment]
I actually ran into two of them in the auto-complete function, then found the conversion rule as you said.  I'm happy to remove the lines.  I was just being "cowardly" in commenting them.

**Review by fedelibre — CHANGES_REQUESTED** [review]
I think we should remove old syntax instead of commenting it. Please remove the lines.
You should also remove `bracketCloseSymbol`. Thanks

**Comment by fedelibre** [comment]
I _think_ you have to `git pull -r origin master` in order to pass the CI checks.

**Comment by fedelibre** [comment]
I've cleaned up the git history and pushed it to your branch. It is now ready to be merged.

**Review by fedelibre — APPROVED** [review]

**Pull request merged**
